### ISSUE TITLE
[bug] Contains allergens emoji not visible in some browsers.

### ISSUE THREAD

**Issue by thinkverse** [safe-menu/translations#1]
## What does this issue contain? 🐛

Inconsistencies with the "Contains allergens" emoji, not being visible on different browsers.

## Suggested resolution for the issue? 🤔

Not sure could be an issue between encodings, or between OS and OS.
Suggest changing the emoji to one that is more universally supported.

### FireFox

![https://menu.safemenu.org/en/business/273/menu/276?category_id=359](https://user-images.githubusercontent.com/2221746/89714408-bac8bf80-d99e-11ea-8e7c-0ae8ea7f5cbc.png)

### Safari

![Safari](https://user-images.githubusercontent.com/2221746/89714389-81904f80-d99e-11ea-8c8d-1384f740303b.png)

### Google Chrome 84

![Google Chrome 84](https://user-images.githubusercontent.com/2221746/89714357-37a76980-d99e-11ea-9ba1-9243ef0618a4.png)

### Brave Browser

![Brave Browser](https://user-images.githubusercontent.com/2221746/89714324-ff079000-d99d-11ea-9081-65a3d98097c9.png)

**Comment by rennokki** [comment]
Oh, I can see it's all about the bacteria emoji. Afaik, digging up on Google led me to understand it's because of the devices that some do not support the bacteria emoji due to some outdated Unicode version.

Have you any idea what I can use to make sure they don't look weird? 🤔

**Comment by thinkverse** [comment]
Just tested on iOS 13 and I can see the emoji there, so It's likely my OS version has an outdated version and, looking it up, it seems yes, the microbe was introduced in Unicode 11, released in 2018 I'm running High Sierra which was released in 2017.

Sadly I cannot find a suitable replacement, maybe 🤧   - that one is from [Unicode v9](https://emojipedia.org/unicode-9.0/) released in 2016 so that would have more support than the microbe, 🤢  would seem a bit harsh I would think personally.

**Comment by rennokki** [comment]
The sneezing emoji looks better than the nauseous one. Gonna update it right now.

Thank you for putting some time to test this issue. ❤️

**Comment by rennokki** [comment]
Got pushed it to production. It should be fine right now on older devices.

https://menu.safemenu.org/en/business/120/menu/128?category_id=164
